### ISSUE TITLE
Not be compatible with Applecore

### ISSUE THREAD

**Issue by 710971956** [djoveryde/Contigo#20]
You will receive NO SUPPORT if you do not follow the template below. (Vous ne receverez pas aucune aide si vous effacer ce modèle)

**Server Log:** *(Use [Pastebin](http://pastebin.com/) or [Github Gist](https://gist.github.com/))*
[17:19:19] [main/INFO]: Loading tweak class name cpw.mods.fml.common.launcher.FMLServerTweaker
[17:19:19] [main/INFO]: Using primary tweak class name cpw.mods.fml.common.launcher.FMLServerTweaker
[17:19:19] [main/INFO]: Calling tweak class cpw.mods.fml.common.launcher.FMLServerTweaker
[17:19:19] [main/INFO]: Forge Mod Loader version 7.99.4.1614 for Minecraft 1.7.10 loading
[17:19:20] [main/INFO]: Java is Java HotSpot(TM) 64-Bit Server VM, version 1.8.0_152, running on Windows 7:amd64:6.1, installed at C:\Program Files\Java\jre1.8.0_152
[17:19:20] [main/INFO]: [pw.prok.imagine.ImagineLoadingPlugin:<clinit>:26]: Loading plugin initialized!
[17:19:21] [main/INFO]: Loading tweak class name cpw.mods.fml.common.launcher.FMLInjectionAndSortingTweaker
[17:19:21] [main/INFO]: Loading tweak class name cpw.mods.fml.common.launcher.FMLDeobfTweaker
[17:19:21] [main/INFO]: Calling tweak class cpw.mods.fml.common.launcher.FMLInjectionAndSortingTweaker
[17:19:21] [main/INFO]: Calling tweak class cpw.mods.fml.common.launcher.FMLInjectionAndSortingTweaker
[17:19:21] [main/INFO]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[17:19:22] [main/INFO]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[17:19:22] [main/INFO]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[17:19:23] [main/INFO]: Calling tweak class cpw.mods.fml.common.launcher.FMLDeobfTweaker
[17:19:23] [main/INFO]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[17:19:23] [main/INFO]: Loading tweak class name cpw.mods.fml.common.launcher.TerminalTweaker
[17:19:23] [main/INFO]: Calling tweak class cpw.mods.fml.common.launcher.TerminalTweaker
[17:19:23] [main/INFO]: Launching wrapped minecraft {net.minecraft.server.MinecraftServer}
[17:19:23] [main/ERROR]: Unable to launch
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_152]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_152]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_152]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_152]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_152]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_152]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_152]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_152]
	at cpw.mods.fml.relauncher.ServerLaunchWrapper.run(ServerLaunchWrapper.java:43) [Contigo-1.7.10-1614.UNOFFICIAL-server.jar:1.7.10-1614.UNOFFICIAL]
	at cpw.mods.fml.relauncher.ServerLaunchWrapper.main(ServerLaunchWrapper.java:12) [Contigo-1.7.10-1614.UNOFFICIAL-server.jar:1.7.10-1614.UNOFFICIAL]
Caused by: java.lang.VerifyError: Expecting a stackmap frame at branch target 94
Exception Details:
  Location:
    net/minecraft/block/BlockSapling.func_149674_a(Lnet/minecraft/world/World;IIILjava/util/Random;)V @36: if_acmpeq
  Reason:
    Expected stackmap frame at this location.
  Bytecode:
    0x0000000: 2bb4 0031 9a01 552a 2b1c 1d15 0419 05b7
    0x0000010: 0033 2a2b 1c1d 1504 1905 b800 393a 0d19
    0x0000020: 0db2 003f a500 3a19 0db2 0042 a601 2d2b
    0x0000030: 1c1d 0460 1504 b600 4610 09a1 011e 1905
    0x0000040: 052b b400 492b b600 4db4 0053 866e 1254
    0x0000050: 6a12 1762 8bb8 005a b600 609a 00fe 2b1c
    0x0000060: 1d15 04b6 0063 360e 2b04 b500 662a 2b1c
    0x0000070: 1d15 0419 05b6 0069 2b03 b500 662b b400
    0x0000080: 6db6 0073 9e00 d5b2 0075 3a06 01b3 0075
    0x0000090: bb00 7759 2bb6 007b 1c87 1d87 1504 87b7
    0x00000a0: 007e 3a07 2bb4 006d b600 82c0 0084 3a08
    0x00000b0: bb00 6f59 b700 853a 0919 08b9 0089 0100
    0x00000c0: 3a0a 190a b900 9101 0099 0023 190a b900
    0x00000d0: 9401 00c0 0096 3a0b 1909 bb00 9859 190b
    0x00000e0: b700 9bb9 009f 0200 57a7 ffd9 2bb4 006d
    0x00000f0: b600 a201 3a0a 1906 c600 1ebb 00a4 5919
    0x0000100: 0719 0603 0119 09b7 00a7 3a0a b800 ad19
    0x0000110: 0ab9 00b3 0200 190a c600 0b19 0ab6 00b6
    0x0000120: 9a00 3919 09b9 0089 0100 3a0b 190b b900
    0x0000130: 9101 0099 0026 190b b900 9401 00c0 00b8
    0x0000140: 3a0c 190c 04b9 00bc 0200 57a7 ffe1 2a2b
    0x0000150: 1c1d 1504 150e b800 c0b1               
  Stackmap Table:
    full_frame(@194,{Object[#2],Object[#45],Integer,Integer,Integer,Object[#92],Object[#139],Object[#119],Object[#132],Object[#132],Object[#141]},{})
    chop_frame(@236,1)
    append_frame(@278,Object[#164])
    same_frame(@291)
    append_frame(@300,Object[#141])
    full_frame(@345,{Object[#2],Object[#45],Integer,Integer,Integer,Object[#92]},{})

	at net.minecraft.block.Block.func_149671_p(Block.java:215) ~[aji.class:?]
	at net.minecraft.init.Bootstrap.func_151354_b(Bootstrap.java:714) ~[kl.class:?]
	at net.minecraft.server.MinecraftServer.main(MinecraftServer.java:1622) ~[MinecraftServer.class:?]
	... 12 more
[17:19:23] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: java.lang.reflect.InvocationTargetException
[17:19:23] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[17:19:23] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[17:19:23] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[17:19:23] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at java.lang.reflect.Method.invoke(Unknown Source)
[17:19:23] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at cpw.mods.fml.relauncher.ServerLaunchWrapper.run(ServerLaunchWrapper.java:43)
[17:19:23] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at cpw.mods.fml.relauncher.ServerLaunchWrapper.main(ServerLaunchWrapper.java:12)
[17:19:23] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: Caused by: cpw.mods.fml.relauncher.FMLSecurityManager$ExitTrappedException
[17:19:23] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at cpw.mods.fml.relauncher.FMLSecurityManager.checkPermission(FMLSecurityManager.java:28)
[17:19:23] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at java.lang.SecurityManager.checkExit(Unknown Source)
[17:19:23] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at java.lang.Runtime.exit(Unknown Source)
[17:19:23] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at java.lang.System.exit(Unknown Source)
[17:19:23] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:138)
[17:19:23] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[17:19:23] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	... 6 more
**FML Log(s):** *(Use [Pastebin](http://pastebin.com/) or [Github Gist](https://gist.github.com/))*
[17:19:19] [main/INFO] [FML/]: Forge Mod Loader version 7.99.4.1614 for Minecraft 1.7.10 loading
[17:19:20] [main/INFO] [FML/]: Java is Java HotSpot(TM) 64-Bit Server VM, version 1.8.0_152, running on Windows 7:amd64:6.1, installed at C:\Program Files\Java\jre1.8.0_152
[17:19:20] [main/INFO] [STDERR/]: [pw.prok.imagine.ImagineLoadingPlugin:<clinit>:26]: Loading plugin initialized!
[17:19:21] [main/INFO] [LaunchWrapper/]: Loading tweak class name cpw.mods.fml.common.launcher.FMLInjectionAndSortingTweaker
[17:19:21] [main/INFO] [LaunchWrapper/]: Loading tweak class name cpw.mods.fml.common.launcher.FMLDeobfTweaker
[17:19:21] [main/INFO] [LaunchWrapper/]: Calling tweak class cpw.mods.fml.common.launcher.FMLInjectionAndSortingTweaker
[17:19:21] [main/INFO] [LaunchWrapper/]: Calling tweak class cpw.mods.fml.common.launcher.FMLInjectionAndSortingTweaker
[17:19:21] [main/INFO] [LaunchWrapper/]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[17:19:22] [main/INFO] [LaunchWrapper/]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[17:19:22] [main/INFO] [LaunchWrapper/]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[17:19:23] [main/INFO] [LaunchWrapper/]: Calling tweak class cpw.mods.fml.common.launcher.FMLDeobfTweaker
[17:19:23] [main/INFO] [LaunchWrapper/]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[17:19:23] [main/INFO] [LaunchWrapper/]: Loading tweak class name cpw.mods.fml.common.launcher.TerminalTweaker
[17:19:23] [main/INFO] [LaunchWrapper/]: Calling tweak class cpw.mods.fml.common.launcher.TerminalTweaker
[17:19:23] [main/INFO] [LaunchWrapper/]: Launching wrapped minecraft {net.minecraft.server.MinecraftServer}
[17:19:23] [main/ERROR] [LaunchWrapper/]: Unable to launch
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_152]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_152]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_152]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_152]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_152]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_152]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_152]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_152]
	at cpw.mods.fml.relauncher.ServerLaunchWrapper.run(ServerLaunchWrapper.java:43) [Contigo-1.7.10-1614.UNOFFICIAL-server.jar:1.7.10-1614.UNOFFICIAL]
	at cpw.mods.fml.relauncher.ServerLaunchWrapper.main(ServerLaunchWrapper.java:12) [Contigo-1.7.10-1614.UNOFFICIAL-server.jar:1.7.10-1614.UNOFFICIAL]
Caused by: java.lang.VerifyError: Expecting a stackmap frame at branch target 94
Exception Details:
  Location:
    net/minecraft/block/BlockSapling.func_149674_a(Lnet/minecraft/world/World;IIILjava/util/Random;)V @36: if_acmpeq
  Reason:
    Expected stackmap frame at this location.
  Bytecode:
    0x0000000: 2bb4 0031 9a01 552a 2b1c 1d15 0419 05b7
    0x0000010: 0033 2a2b 1c1d 1504 1905 b800 393a 0d19
    0x0000020: 0db2 003f a500 3a19 0db2 0042 a601 2d2b
    0x0000030: 1c1d 0460 1504 b600 4610 09a1 011e 1905
    0x0000040: 052b b400 492b b600 4db4 0053 866e 1254
    0x0000050: 6a12 1762 8bb8 005a b600 609a 00fe 2b1c
    0x0000060: 1d15 04b6 0063 360e 2b04 b500 662a 2b1c
    0x0000070: 1d15 0419 05b6 0069 2b03 b500 662b b400
    0x0000080: 6db6 0073 9e00 d5b2 0075 3a06 01b3 0075
    0x0000090: bb00 7759 2bb6 007b 1c87 1d87 1504 87b7
    0x00000a0: 007e 3a07 2bb4 006d b600 82c0 0084 3a08
    0x00000b0: bb00 6f59 b700 853a 0919 08b9 0089 0100
    0x00000c0: 3a0a 190a b900 9101 0099 0023 190a b900
    0x00000d0: 9401 00c0 0096 3a0b 1909 bb00 9859 190b
    0x00000e0: b700 9bb9 009f 0200 57a7 ffd9 2bb4 006d
    0x00000f0: b600 a201 3a0a 1906 c600 1ebb 00a4 5919
    0x0000100: 0719 0603 0119 09b7 00a7 3a0a b800 ad19
    0x0000110: 0ab9 00b3 0200 190a c600 0b19 0ab6 00b6
    0x0000120: 9a00 3919 09b9 0089 0100 3a0b 190b b900
    0x0000130: 9101 0099 0026 190b b900 9401 00c0 00b8
    0x0000140: 3a0c 190c 04b9 00bc 0200 57a7 ffe1 2a2b
    0x0000150: 1c1d 1504 150e b800 c0b1               
  Stackmap Table:
    full_frame(@194,{Object[#2],Object[#45],Integer,Integer,Integer,Object[#92],Object[#139],Object[#119],Object[#132],Object[#132],Object[#141]},{})
    chop_frame(@236,1)
    append_frame(@278,Object[#164])
    same_frame(@291)
    append_frame(@300,Object[#141])
    full_frame(@345,{Object[#2],Object[#45],Integer,Integer,Integer,Object[#92]},{})

	at net.minecraft.block.Block.func_149671_p(Block.java:215) ~[aji.class:?]
	at net.minecraft.init.Bootstrap.func_151354_b(Bootstrap.java:714) ~[kl.class:?]
	at net.minecraft.server.MinecraftServer.main(MinecraftServer.java:1622) ~[MinecraftServer.class:?]
	... 12 more
[17:19:23] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: java.lang.reflect.InvocationTargetException
[17:19:23] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[17:19:23] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[17:19:23] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[17:19:23] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at java.lang.reflect.Method.invoke(Unknown Source)
[17:19:23] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at cpw.mods.fml.relauncher.ServerLaunchWrapper.run(ServerLaunchWrapper.java:43)
[17:19:23] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at cpw.mods.fml.relauncher.ServerLaunchWrapper.main(ServerLaunchWrapper.java:12)
[17:19:23] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: Caused by: cpw.mods.fml.relauncher.FMLSecurityManager$ExitTrappedException
[17:19:23] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at cpw.mods.fml.relauncher.FMLSecurityManager.checkPermission(FMLSecurityManager.java:28)
[17:19:23] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at java.lang.SecurityManager.checkExit(Unknown Source)
[17:19:23] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at java.lang.Runtime.exit(Unknown Source)
[17:19:23] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at java.lang.System.exit(Unknown Source)
[17:19:23] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:138)
[17:19:23] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[17:19:23] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	... 6 more
**Explanation of issue:**

**How to recreate this issue:**

**Modpack Name:** *(Only if public)*

**Mods Installed:**
AppleCore-mc1.7.10-3.1.0
**Plugins Installed:**
No
**Warmroast Report:** *(Optional)*

**Thermos Version:**
Contigo R59
**Forge Version:**
1614

**Comment by Bogdan-G** [comment]
add jvm argument: `-noverify`
